### ISSUE TITLE
Shell for 1.6mm PCB (not a bug report)

### ISSUE THREAD

**Issue by remy** [Staacks/gbinterceptor#10]
After going backwards and forwards through JLCPCB I managed to accidentally order 1.6mm thick PCB - which obviously doesn't fit anything properly 🤦 - but I ended up creating a new shell to compensate for my mess up. I wasn't sure if you wanted to include it in the wiki (or whether you'd be happy for me to do a PR on the wiki…not sure how, but I'll learn).

URL is here: https://www.printables.com/model/371833-gb-interceptor-shell-for-16mm-pcb

Obviously ideally people get the right thickness though! 😄

**Comment by Staacks** [comment]
Sure, that might help others in the same situation. I have added it to the Wiki.
