### ISSUE TITLE
Add Super Game Boy 2 and Analogue Super Nt to the Game Boy compatibility list

### ISSUE THREAD

**Issue by techknight** [Staacks/gbinterceptor#19]
**Describe the bug**
I did a quick test of the GB Interceptor on the Super Game Boy 2 using a Super Famicom and an Analogue Super Nt, and Kirby's Pinball Land played as expected on both setups.

**Screenshots**
[Video capture of Kirby's Pinball Land on GB Interceptor on Super Game Boy 2 on Super Nt](https://www.youtube.com/watch?v=NKL3w_MLFaw)

**Game Boy:**
- Model: Super Game Boy 2

**Game:**
- Title: Kirby's Pinball Land
- Version: DMG-K9-USA-1

**Additional context**
The Super Game Boy 2 is a later revision of the Super Game Boy that runs at the correct speed. (The original Super Game Boy is slightly slower than a real Game Boy.)

**Comment by Staacks** [comment]
Thanks for the feedback! I have added the SGB2.

(Not adding the Super Nt separately because I don't think that the host system of the SGB2 should play a role for the Interceptor.)
