### ISSUE TITLE
showed waiting the game.....

### ISSUE THREAD

**Issue by hpx1984** [Staacks/gbinterceptor#22]
Hi Sir

many thanks your hard working on this great project 

now i built one and every thing seems good 
but i just can saw the screen of "waiting the game....." or "game boy turned off"

where i can check to try to fix this issue?

**Comment by hpx1984** [comment]
more information

i can saw the device on PC
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/4d80549f-1600-4a81-b194-2690745a9aa1)
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/d322e8e0-e210-48d5-bb17-c3f2cfc556e6)

FW:1.2.0
Turned off GameBoy
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/8f0dd075-bbb0-456f-8f81-5e228e16313d)

Turned on Game Boy ,the game boy working as normal but PC screen showed "waiting for game"
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/cb7f494a-c039-47f8-bbb6-f7b3b5ae899e)

Interceptor status:
PWR Blue LED on,and another red LED is flash 
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/be3c440c-ffa4-4835-ab18-2219c994262b)

![image](https://github.com/Staacks/gbinterceptor/assets/76941051/8c79a8be-1fcb-459d-844c-9011e362198d)
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/2e0b1adf-4838-40c8-bd41-5d7859e48f38)

Sir ,any time ,please help me if you got my message and if you have free time

**Comment by hpx1984** [comment]
hi Sir

i found the problem is on the flash IC , now fixed the problem and it can working 
![image](https://github.com/Staacks/gbinterceptor/assets/76941051/9e5d8154-93f6-4340-87af-a44cea4dde51)

**Comment by Staacks** [comment]
Glad you found the problem :)
