### ISSUE TITLE
Does not recognize second boot on special cartridges with menus (i.e. Everdrive, Game Genie, etc.)

### ISSUE THREAD

**Issue by Staacks** [Staacks/gbinterceptor#4]
The Interceptor waits for a request to address 0x0100 to recognize the start of the game. When there is an error or the game halts too long, it shows an info screen, but will not again wait for 0x0100 unless the Game Boy is turned off and on again. While this makes sense for regular games, it interferes with some special cartridges, that show a menu before loading a game and reset without turning off.

To fix this, the Interceptor simply needs to allow for a second boot within a short time frame.

**Workaround until this is fixed:**
Plug in the USB cable for the Interceptor when the special cartridge is already showing its menu.
(This way it misses the first 0x0100 and starts with the 0x0100 from the actual game. You won't see the menu on the Interceptor, though.)

**Comment by Staacks** [comment]
Uhm... github was a bit fast here. I leave it open until someone with an Everdrive reports back.

**Comment by Staacks** [comment]
Confirmed to fix the problem for the Everdrive.

**Comment by domis4** [comment]
have this issue with the EZ Flash JR. (besides the already known graphical issues)

can i support or help here?

![Bildschirm­foto 2023-04-03 um 18 43 25](https://user-images.githubusercontent.com/16278030/229574138-b21fa683-a306-44ab-858f-4d5866d14c6b.png)

**Comment by Staacks** [comment]
Wait, this only happens when the EZ Flash reboots? This looks exactly like the MacOS problem on M1 and M2 macs and the original EZ Flash problem was already resolved a while ago and was simply the problem that the Interceptor did not recognize that the Game Boy restarted and was stuck on the error screen. This is a USB Video problem and I am scratching my head how it would be related to a reboot of the EZ flash. Also, I am using an EZ Flash Jr. all the time to test game-specific problems...

So, let's start collecting a few details:
- Which firmware are you using (and if not the latest, please try the latest one).
- Can you tell me step by step what you do and what the Interceptor shows? Especially, what part looks correct, which status/error screens are shown (even for a fraction of a second) and what the blue LED on the back does.
- Can you also show a Windows screenshot? I am wondering if it is the MacOS issue on Windows, too, or if we are looking at two problems at the same time.
-

**Comment by domis4** [comment]
My steps where the following and reproduceable:

Windows 11:
1. Plug in Everything (GB Interceptor into GBC, Cardridge into GB Interceptor, USB C into Windows 11 PC)
(no LED)
2. Launch OBS and select a new Scene with the GB Interceptor 
(no LED)
3. Power on the Gameboy, wait until the screen is visible in OBS
(red LED, until OBS picked a signal, then both LED)
4. Launch a Game
(red LED only)

![IMG_6994](https://user-images.githubusercontent.com/16278030/229617247-f5c4b4b8-823c-4801-9469-c31e43496427.jpeg)
![IMG_6995](https://user-images.githubusercontent.com/16278030/229617270-9b25d18f-ed82-4b1d-995f-5526ab690154.jpeg)
![IMG_6997](https://user-images.githubusercontent.com/16278030/229617583-ba714b7f-690c-4a63-a48c-9b89cf4bd9c8.jpeg)
![IMG_6998](https://user-images.githubusercontent.com/16278030/229617655-278cf493-8d5b-4073-a302-31869e93aacb.jpeg)

**Comment by Staacks** [comment]
Thank you for your e-mail. I will be out of office until 11th April and my response may take longer than usual.

Best regards,
Sebastian Staacks

**Comment by Staacks** [comment]
Thanks, so the green video problem is the known MacOS issue. (Or is the EZ Flash menu normal on the Mac?)

But I am afraid that Pokemon Crystal is not a good example, because that is a Game Boy Color game which is not supported by the Interceptor. I would guess that the error is not from the second boot but from the GBC game entering double speed mode. Do you have the problem with classic games, too?

**Comment by domis4** [comment]
well, thats embarrsing. It works perfectly on .gbc games 🤦‍♀️ how could i forget that crystal is a gbc only game. Thanks for your fast replies!
